### ISSUE TITLE
什么时候加入proj.win32工程？

### ISSUE THREAD

**Issue by puckery** [dualface/v3quick#121]
如题

**Comment by SunLightJuly** [comment]
工程模板已经简化，不再加入proj.win32。如果需要在windows下调试，使用player就可以了。

**Comment by puckery** [comment]
这有点不科学吧？我们现在的工程都是用proj.win32来开发的，不是直接用player

**Comment by SunLightJuly** [comment]
如果你确实需要，把player下的proj.win32目录复制到自己的工程目录下是可以用的

**Comment by puckery** [comment]
好的，谢谢。不过建议还是加上proj.win32，还是很多人需要的。

**Comment by tengontheway** [comment]
是啊 大的工程这个还是非常必要的
