### ISSUE TITLE
Can not resize player screen  - macbook pro 17, mac os x 10.9.4

### ISSUE THREAD

**Issue by takaaptech** [dualface/v3quick#125]
Hi,
When launch player, it shows big size window and i can not resize it to normal, please fix! Thank so much!
![screen shot 2014-09-09 at 3 34 58 pm](https://cloud.githubusercontent.com/assets/6276251/4198687/350cc82c-37fc-11e4-81a5-7d50b5916b3c.png)

**Comment by fiskercui** [comment]
open the file 'AppController.mm' in the method 'createWindowAndGLView',
    float screenScale = [[NSScreen mainScreen] backingScaleFactor];
you can change the screenScale to affect the effect, for example(set screenScale to 1.0f):
    screenScale = 1.0f;

**Comment by dualface** [comment]
fixed
