### ISSUE TITLE
vs2012 player编译错误

### ISSUE THREAD

**Issue by puckery** [dualface/v3quick#129]
2>glfw3.lib(win32_time.obj) : error LNK2019: 无法解析的外部符号 __dtoul3，该符号在函数 __glfwPlatformSetTime 中被引用
2>glfw3.lib(win32_time.obj) : error LNK2019: 无法解析的外部符号 __ultod3，该符号在函数 __glfwInitTimer 中被引用

**Comment by SunLightJuly** [comment]
因为player的功能需要，glfw3.lib这个库刚重新做了编译。因为是在vs2013下编译的，所以现在在2012上用不了。稍后会处理此问题。

**Comment by SunLightJuly** [comment]
已经解决
