### ISSUE TITLE
print 在 android 真机下不输出任何内容

### ISSUE THREAD

**Issue by uhoohei** [dualface/v3quick#130]
在player下可以正常输出，在android真机下不输出，无任何反应。

**Comment by skyblue** [comment]
不能输出是因为build_native.sh里默认注释了NDK_DEBUG=1
ps:建议默认打开并输出提示,发布的时候再另行处理.

**Comment by SunLightJuly** [comment]
工程模板里的build_native确实默认了不打开调试输出
