### ISSUE TITLE
android 真机使用 luaj 时 args 参数不能为nil, 否则APP直接挂掉

### ISSUE THREAD

**Issue by uhoohei** [dualface/v3quick#131]
原来args参数可以为nil, 现在如果为空的话必须为 {} , 我觉得这里应该说明一下，或者判断一下，不然从2.X升级过来的时候被这个坑惨了。

**Comment by SunLightJuly** [comment]
如果你调用的是luaj.callStaticMethod()，第三个参数应该是可以为nil的。请问你是如何遇到的问题呢？

**Comment by bigHandYT** [comment]
local javaMethodName = "needInitPlatform"
local javaParams = { }
local javaMethodSig = "()Z"
local ok, ret = luaj.callStaticMethod(Launcher.javaClassName, javaMethodName, javaParams, javaMethodSig)

应该是javaParams = nil crash 需要设置成一个空的table。

**Comment by hugohuang1111** [comment]
检查了luaj.lua的代码,当javaParams不为table时，都会把它重置为空表的

local function checkArguments(args, sig)
if type(args) ~= "table" then args = {} end
... ...
end

**Comment by hugohuang1111** [comment]
再次检查没重现,看代码对args为nil也是作了处理的
