### ISSUE TITLE
FileUtils::getFileData未bind lua

### ISSUE THREAD

**Issue by sishui** [dualface/v3quick#141]
在使用cc.utils.Gettext.gettextFromFile的时候
回报 getFileData() 是 nil

**Comment by SunLightJuly** [comment]
FileUtils::getFileData()在cocos2dx 3.x里已经被标注为不建议使用的接口，也没有进行导出。读取文本类文件现在可以使用cc.FileUtils:getStringFromFile；读取二进制文件可以使用cc.HelperFunc:getFileData()。
cc.utils.Gettext里的调用将会改过来。

**Comment by skyblue** [comment]
FileUtils::getFileDataFromZip 也没有导出
另外proj.android编译

```
quick-cocos2d-x-V3/cocos/./platform/CCImage.cpp:34:33: fatal error: apptools/HelperFunc.h: No such file or directory
 #include "apptools/HelperFunc.h"
```
