### ISSUE TITLE
mac执行

### ISSUE THREAD

**Issue by liqt** [dualface/v3quick#151]

**Comment by liqt** [comment]
只会更新下面这些目录：
updating all framework_precompiled.zip

samples/anysdk/res/framework_precompiled.zip
samples/tests/res/framework_precompiled.zip
samples/touch/res/framework_precompiled.zip
templates/PROJECT_TEMPLATE_01/res/framework_precompiled.zip

**Comment by SunLightJuly** [comment]
目前脚本执行的过程是这样的：
1、在lib/framework_precompiled/下创建最新的framework_precompiled.zip
2、在sample下搜索所有的framework_precompiled.zip，用最新的替换；这里多数sample原来就去掉了zip，默认在player下运行，所以目前需要更新的只有三个
3、更新工程模板中的zip
不知你觉得还有哪个地方需要更新但还没有更新的呢？

**Comment by liqt** [comment]
我项目的目录再quick/myproject目录下。 我认为搜索路径至少应该是quick目录或者v3quick目录下的吧。
或者给用户提供一个参数，可以指定额外的输出目录。
