### ISSUE TITLE
UIPushButton如果只设置norm一个image状态时， 再按下的button时需要设置一个透明度

### ISSUE THREAD

**Issue by liqt** [dualface/v3quick#186]
如题，这样很多情况下都只设置一个图片就行了。

**Comment by skyblue** [comment]
这种的在onButtonPress回调里都可以处理，缩放变灰半透明 怎么做都行

发自我的 iPhone

**Comment by liqt** [comment]
但我觉得这应该是控件的一部分功能，而不是交由用户实现。

**Comment by bigHandYT** [comment]
可以仿照ccs里面的默认是缩放,修改了代码就可以满足了。

**Comment by hugohuang1111** [comment]
现在先自己设置吧,每个项目想要的需求都不一样
