### ISSUE TITLE
建议接口注释说明参数类型，尤其回调函数

### ISSUE THREAD

**Issue by liqt** [dualface/v3quick#187]
例如下面这个回调函数是什么样的回调函数， 接受那些参数及参数类型

--[[--

注册用户点击监听

@param function callback 监听函数

@return UIButton

]]
function UIButton:onButtonClicked(callback)
    self:addButtonClickedEventListener(callback)
    return self
end

**Comment by hugohuang1111** [comment]
感谢提的这个建议
