### ISSUE TITLE
debug_win.bat判断player是否存在无效

### ISSUE THREAD

**Issue by IpWoo** [dualface/v3quick#199]
if not exist "BIN" set BIN=%QUICK_V3_ROOT%quick\player\proj.win32\Release\player3.exe
if not exist "BIN" set BIN=%QUICK_V3_ROOT%quick\player\proj.win32\Debug\player3.exe
把 "BIN" 改成 %BIN%
if not exist %BIN%set BIN=%QUICK_V3_ROOT%quick\player\proj.win32\Release\player3.exe
if not exist %BIN% set BIN=%QUICK_V3_ROOT%quick\player\proj.win32\Debug\player3.exe

**Comment by SunLightJuly** [comment]
已经修改
