### ISSUE TITLE
win7下无法编译通过android版本

### ISSUE THREAD

**Issue by lity** [dualface/v3quick#202]
Application.mk 中如果将

CC_USE_CURL := 1
CC_USE_JPEG := 1
CC_USE_TIFF := 1
CC_USE_WEBP := 1
CC_USE_TGA := 1
CC_USE_PHYSICS := 1
CC_USE_WEBSOCKET := 1
CC_USE_JSON := 1
CC_USE_SQLITE := 1
CC_USE_CCS_ARMATURE := 1
CC_USE_EXTRA_FILTERS := 1
全部或部分改为
0

则无法正确完成编译，只有全部设为1才能通过编译

**Comment by SunLightJuly** [comment]
你没有把对应的APP_CPPFLAGS参数设置成0吧，要象下面这样：

QUICK_CURL_ENABLED := 0
APP_CPPFLAGS += -DQUICK_CURL_ENABLED=0

**Comment by lity** [comment]
是的，我把 APP_CPPFLAGS 也设置成0就好了。
