### ISSUE TITLE
win player，按钮点不了

### ISSUE THREAD

**Issue by sishui** [dualface/v3quick#215]
环境windows, 屏幕分辨率1366*768（笔记本）
用player 新建工程 里面添加按钮代码

```
    cc.ui.UIPushButton.new({normal = "Button.png"})
            :onButtonClicked(function()
                print("clicked")
            end)
            :pos(display.width/2, display.height/2-150)
            :addTo(self)
```

点击按钮无效

设置player zoom 50%， 点击有效

**Comment by hugohuang1111** [comment]
player的分辨率是多少呢,config.lua是怎么样的呢

我们没有重现此问题

**Comment by ghost** [comment]
谢谢反馈, 当 player 的高度小于屏幕高度时, 窗口高度被系统调整了 (player 的高度变小) .
OpenGL 凌乱了.

**Comment by sishui** [comment]
@htlxyz, player 是默认分辨率，记得是iPhone4s 的，竖屏

**Comment by dualface** [comment]
新的 simulator 应该没有这个问题了。
