### ISSUE TITLE
在quick里使用lua协程, 在使用crypto.md5 /encodeBase64等binding方法时返回值异常

### ISSUE THREAD

**Issue by skyblue** [dualface/v3quick#234]
在quick里使用lua协程, 在使用crypto.md5 /encodeBase64等binding方法时返回值异常
之前没注意到还有这个问题…(这就断了我用协程的念头吗?)

local co = coroutine.create(function()
    coroutine.yield(123);
    local r1 = crypto.md5(123)
    coroutine.yield(r1);
    local r2 = json.encode({1,2,3})
    coroutine.yield(r2);
    return "co end~~"
end)

print("outside - crypto.md5(123)", crypto.md5(123) )
print("yield(123)", coroutine.resume(co))
print("crypto.md5(123)", coroutine.resume(co))
print("json.encode({1,2,3})",coroutine.resume(co)) — 这个是正常的
print("co end?",coroutine.resume(co))
print("should dead~",coroutine.resume(co))

**Comment by dualface** [comment]
cocos 调用 lua 的方式会中断协程，所以在 cocos2dx-lua 里不要用协程。

**Comment by skyblue** [comment]
真是杯具~
只是似乎其他功能一直都使用正常, 目前也只遇上crypto这块有问题~
binding实现上有什么区别吗?
