### ISSUE TITLE
void Node::addChild(Node* child, int localZOrder, const std::string &name)

### ISSUE THREAD

**Issue by skyblue** [dualface/v3quick#240]
## 这个接口没有导出? 

sorry   是有的
只是调用会触发一条 
cocos2d: LUA ERROR: luaval_to_native_err()

**Comment by SunLightJuly** [comment]
嗯，是cocos绑定代码里的bug，尝试第一种参数组合时出错会提示，但实际上还是会尝试第二种参数组合并成功调用
