### ISSUE TITLE
Can we using framework FB from cocos2dx with v3quick 

### ISSUE THREAD

**Issue by takaaptech** [dualface/v3quick#261]
Just for sure, can we using build in FB from here http://www.cocos2d-x.org/news/368 with v3quick?
Thanks!

**Comment by dualface** [comment]
CAN NOT. Because FB connector use JavaScript.

**Comment by takaaptech** [comment]
I mean facebook framework for login, query .. like here:
http://www.cocos2d-x.org/wiki/Facebook_Support_for_Cocos2d-x_Beta
do we support this?

**Comment by dualface** [comment]
I think you should integration this plugin by yourself.
