### ISSUE TITLE
v3版本的player是不是不再支持LDT调试了?

### ISSUE THREAD

**Issue by thinkry** [dualface/v3quick#262]
我使用3.2RC1版本的quickx，能在CodeIDE里调试，LDT里调试器能连上，但无法断点。我发现debugger.c在2.2.x版本和3.2版本有差异，请问是不是v3版本不在支持LDT调试了？

**Comment by dualface** [comment]
这个 debugger.c 是适合 Code IDE 的。3.3 目前不支持 LDT。
