### ISSUE TITLE
node:getAnchorPointInPoints() 返回值不对

### ISSUE THREAD

**Issue by xpol** [dualface/v3quick#274]
测试代码：

``` Lua
label:setAnchorPoint(0.5,-1)
local p = label:getAnchorPointInPoints()
print(p.x, p.y)
```

输出是：

```
cocos2d: 0  -0
```

**Comment by hugohuang1111** [comment]
label:setAnchorPoint(0.5,-1)
local p = label:getAnchorPoint() -- getAnchorPointInPoints()
print(p.x, p.y)

**Comment by hugohuang1111** [comment]
不好意思,刚理解错了,
应该是设置了contentSize后没有更新anchorPointInPoints导致的

**Comment by hugohuang1111** [comment]
仔细跟了下,
setAnchorPoint后,立刻调用getAnchorPoints,这时contentSize是没有值的,所以会是0,

要在这个node渲染时,才会更新contentSize,也就是在当label画出来后,getAnchorPointIPoints才有正确的值
