### ISSUE TITLE
UIListView PageView 坐标转换不正确

### ISSUE THREAD

**Issue by song920** [dualface/v3quick#279]
UIListView PageView 坐标转换不正确，当view添加到子容器的时候，不能正确转换坐标，导致可能无法显示touch失效

 viewRect = cc.rect(40, 80, 120, 400) rect设置必须为全局world坐标系，应该设置为相对坐标

**Comment by hugohuang1111** [comment]
viewRect = cc.rect(40, 80, 120, 400)用的就是相对坐标,
检查下你的代码是否正确呢

**Comment by bigHandYT** [comment]
我这边也是绝对坐标，3.2版本的。

**Comment by hugohuang1111** [comment]
在样例中listview的位置没有设置过,那它就是在原点,左下角,这样就会感觉它用的是全局坐标系

可以给它设置一个位置,看它会不会移动,就可以看出来了
