### ISSUE TITLE
v3quick player编译出错

### ISSUE THREAD

**Issue by liqiangpro** [dualface/v3quick#286]
环境：osx 10.10、xcode6.1

/Users/xxxx/Documents/Project/v3quick/quick/player/proj.mac/AppController.mm:276:25: error: cannot initialize a parameter of type 'id<NSFileManagerDelegate>' with an lvalue of type 'AppController *'
    [NSApp setDelegate: self];
                        ^~~~
In file included from /Users/xxxx/Documents/Project/v3quick/quick/player/proj.mac/AppController.mm:1:
In file included from /Users/xxxx/Documents/Project/v3quick/quick/player/proj.mac/Prefix.pch:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:31:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:109:47: note: passing argument to parameter 'delegate' here
@property (assign) id <NSFileManagerDelegate> delegate NS_AVAILABLE(10_5, 2_0);
                                              ^
1 error generated.

**Comment by ghost** [comment]
see #272
