### ISSUE TITLE
C++对象内存无法释放

### ISSUE THREAD

**Issue by puckery** [dualface/v3quick#287]
测试例子：
    collectgarbage("collect")
    -- 5600.0302734375
    print("1:",collectgarbage("count"))
    for i=1,50000 do
         local p = cc.Node:create()
    end
    print("2:",collectgarbage("count"))
    collectgarbage("collect")
    -- 11061.815429688
    print("3:",collectgarbage("count"))

增加的内存无法被释放！

**Comment by dualface** [comment]
只要不是在同一帧里连续创建对象就不会有问题。你会在一帧里创建50,000个对象吗？不会。

**Comment by puckery** [comment]
如果每次关闭再打开创建50个，那这些多余的内存怎么消除？
是否有办法强制清除？

**Comment by dualface** [comment]
上一帧里创建的对象没用到的会自动释放，下一帧再创建其他的不会导致内存增加。
