### ISSUE TITLE
quick-3.3rc0 在iPhone 5s/6/6plus是不能运行

### ISSUE THREAD

**Issue by zhangzpap** [dualface/v3quick#310]
luac from cocos2d-x 3.3rc0 console's luacompile cant not run on iPhone5s\iPhone6(64bit devices)

**Comment by SunLightJuly** [comment]
现在带的luac是32位的。需要用64位编译的话，只能先用lua源码，不要打包了。

**Comment by SunLightJuly** [comment]
请使用3.3final版本
