### ISSUE TITLE
EventProxy之中的两个函数实现错误。

### ISSUE THREAD

**Issue by tangyiyang** [dualface/v3quick#315]
1. framework/cc/EventProxy.lua 23行
   函数： function EventProxy:removeEventListener(eventName, key1, key2)
   之中的第24行  
   local removeHandle = self.eventDispatcher_:removeEventListener(eventName, key1, key2)
   调用EventDispatcher的removeEventListener,但是在 eventDispatcher是一个EventProtocal对象，EventProtocal中并没有这个函数（removeEventListener(eventName, key1, key2)）
2. 同样是在EventProxy.lua 34行
   函数： function EventProxy:removeAllEventListenersForEvent(eventName) 
   之中的第37行，
            self.eventDispatcher_:removeEventListener(handle[1], handle[2])
   这一行代码应该是调用 EventProtocal.removeEventListenersByEvent(eventName) 这个函数。

：）

**Comment by hugohuang1111** [comment]
fixed
