### ISSUE TITLE
Native c# and LUA binding for wp8 build?

### ISSUE THREAD

**Issue by takaaptech** [dualface/v3quick#316]
Hi,
does v3quick support communication between c# and LUA yet? Please give us an example, thank so much!

**Comment by ghost** [comment]
not yet

**Comment by SunLightJuly** [comment]
v3quick is able to run on wp8 now

**Comment by takaaptech** [comment]
I wish there will be a luacsharpbridge sample soon...

**Comment by dualface** [comment]
暂时没有这样的扩展功能。

Windows Phone 由于市场占有率太低，所以功能开发的优先级也很低。
