### ISSUE TITLE
quick-x经常因为LuaEventNode在C++中崩溃

### ISSUE THREAD

**Issue by starwing** [dualface/v3quick#318]
在我们的项目里面很常见。经过调试崩溃在LuaTouchEventManager.cpp里面：

``` cpp
        do
        {
            isTouchable = isTouchable
                && checkTouchableNode->isRunning() // 这里
                && checkTouchableNode->isVisible()
                && checkTouchableNode->isTouchCaptureEnabled();
            checkTouchableNode = checkTouchableNode->getParent();
        } while (checkTouchableNode && isTouchable);
        if (!isTouchable) continue;
```

经过调试，貌似是因为Node本身已经被deleted掉了（内存里是0xFEEEFEEE），但是LuaNode还在（而且引用是2），经常在切换场景之后点空白区域就挂了，求解决方案……

**Comment by starwing** [comment]
今天又有陆续几个地方崩溃，也是同样的原因，但是是在这里：

``` cpp
void LuaTouchEventManager::dispatchingTouchEvent(const std::vector<Touch*>& touches, Event *pEvent, int event)
{
    LuaEventNode *node = nullptr;
    LuaTouchTargetNode *touchTarget = nullptr;
    Touch *touch = nullptr;

    ssize_t count = _touchingTargets.size();
    //    CCLOG("TOUCH TARGETS COUNT [%u]", count);
    for (ssize_t i = 0; i < count; ++i)
    {
        touchTarget = _touchingTargets.at(i);

        if (!touchTarget->getNode()->isRunning()) // 这里
        {
            // target removed from scene, remove it
```

崩溃的原因还是_node被释放掉了，但是LuaEventNode的引用计数是1……

**Comment by SunLightJuly** [comment]
3.3rc0版本确实有此问题，在之后已经得到了修改。在新版本出来之前，你可以先这样处理:
更新此目录下的文件：https://github.com/dualface/v3quick/tree/v3/external/lua/quick
再更新此文件：https://github.com/dualface/v3quick/blob/v3/quick/framework/cocos2dx/NodeEx.lua

**Comment by dualface** [comment]
我们明天就检查。如果有问题，本周内修复。
2014年11月24日 下午11:35于 "Xavier Wang" notifications@github.com写道：

**Comment by starwing** [comment]
好的，今天已经覆盖，不过发现一个问题，在NodeEx.lua的294行：这里应该是个冒号吧？是故意的还是typo？

``` lua
                    self.removeNodeEventListenersByEvent(evt)
```

**Comment by SunLightJuly** [comment]
这里确实是个疏漏，谢谢指出！

**Comment by liqiangpro** [comment]
最新版的代码还是偶尔会在此处crash
 // check node is visible and capturing enabled
        isTouchable = true;
        do
        {
            isTouchable = isTouchable
                && checkTouchableNode->isRunning() // 这里，报EXC_BAD_ACCESS
                && checkTouchableNode->isVisible()
                && checkTouchableNode->isTouchCaptureEnabled();
            checkTouchableNode = checkTouchableNode->getParent();
        } while (checkTouchableNode && isTouchable);
        if (!isTouchable) continue;

bool LuaEventNode::isRunning() const
{
    if (_node)
    {
        return _node->isRunning(); // 这里，报EXC_BAD_ACCESS
    }
    return false;
}

**Comment by kawaiSky** [comment]
在node执行过setTouchEnabled(true)之后没有触发 cleanup就被release掉的时候 确实会出现这个问题.

**Comment by liqiangpro** [comment]
没懂，请教下如何避免？

**Comment by kawaiSky** [comment]
这个 你可以看看这个帖子 http://www.cocoachina.com/bbs/read.php?tid=274154#1193929
是我之前遇到的问题。
而且其实我现在的应用还是不确定什么时候就会出现一次这样的崩溃。只是频率已经很小了。

**Comment by liqiangpro** [comment]
嗯，几率是很小，但是问题还是有的，感谢回复。也希望开发团队能重视下这个问题。

**Comment by liqiangpro** [comment]
嗯，感谢回复。我的情况应该是类似，调整UI的时候，创建了一个UIPushButton，没有retain，也没有add到舞台。
