### ISSUE TITLE
关于UIPageView切换场景完后有一定概率不响应触摸事件

### ISSUE THREAD

**Issue by starwing** [dualface/v3quick#319]
我们这边用UIPageView做关卡列表，每一项里面放了一个cocostudio出来的UI，在切换场景之后，某一些UIPageViewItem不知道为什么突然有了触摸事件，但是它本身不响应而且吞噬了下面的事件，导致UIPageView无法点击、拖动。

之前以为是LuaNodeEvent的那个问题，但是在替换了新的代码以后，仍然有这个现象 :(

**Comment by hugohuang1111** [comment]
从描述看来,就是UIPageViewItem中的内容吞噬了事件,
为什么会吞噬,是什么原因,可能要根据Item中具体的内容来判断,
可以的话,给我们一个测试例子

**Comment by starwing** [comment]
没问题~我们这边整理一下给你发一个测试样例，不过现在还在赶工，所以只能赶工以后再发了 :(

UIPageViewItem里面有个Panel，Panel是用cocosstudio导出用uiloader加载的，刚开始的时候发现Panel顶上有个“交互”，不过后来已经干掉了，里面只有image和label，没有任何交互。我们这边如果一开始就递归设置setTouchEventEnabled(false)后就没问题了，但是问题是这里是关卡列表，我们有很多节点在这里。

其实如果是第一次就不响应也就算了，问题是，第一次一定是好的，经过了反复三四次切换界面以后，在大概一百来个中，总会有几个Node会出现事件交互，这部分我们以后会优化，但是这证明这是个概率事件——所有的节点都是以相同的方法创建出来的，但是最终有些会吞噬事件。

而且吞噬中呈现一些特殊的现象，比如如果5号和7号不接受事件，那么4也不接受这种。

另外，对于UIPageView以及UIListView，因为有可能会增加很多项，能不能提供一个类似Android的ListView的Adapter的接口呢？具体就是，提供一个Adapter类，这个类有这么几个方法：
- 创建新的节点
- 设置节点数据
- 返回节点数量
- 返回特定节点类型

这样，ListView和UIPageView内部就可以做到节点的复用了。这样比较省内存。如果你们这边计划上跟不上，我们这边做完了可能会考虑做一个这个东西然后PR给你们。

非常感谢！

**Comment by hugohuang1111** [comment]
listview的异步加载最新的代码中已经加上了,在ui这个例子中新加了它的用法
