### ISSUE TITLE
官网新版本quick-x3.3编译安卓的时候没有指导，各种参数不明白什么意思

### ISSUE THREAD

**Issue by wijat** [dualface/v3quick#327]
打开player，一个做好的项目，点击编译，会发现Android：标记下面的几个参数

ANDROID_PLATFORM： NDK_MODE：
APP_ABI： TOOLCHAIN：
CPPFLAGS：

这几个参数不懂怎么填，对于我这种菜B来说我以为可以不填就一键编译，结果不填就弹编译不成功。
Running command: compile
 There isn't any available platforms

然后我就知道惨了........不知道什么原因。
PS: docs文件夹里面的API已经老了，新版的3.3不懂怎么编译安卓apk，我是刚刚从2dx转来用quick的。

**Comment by wijat** [comment]
付个图
![qq 20141127154211](https://cloud.githubusercontent.com/assets/8220843/5214032/6b88f590-7651-11e4-84fc-db287cc58a19.jpg)
![qq 20141127154309](https://cloud.githubusercontent.com/assets/8220843/5214042/8ac9f9b8-7651-11e4-98a9-a82100df574c.jpg)

**Comment by hugohuang1111** [comment]
android platform
ndk mode
app_abi
这些一般可以不用设置,它们就是对应的cocos compile的参数
如果想看他们的更详细的含义,可以命令行中运行 "cocos compile -h" 查看

"There isn't any available platforms"
这个错应该是 platform cocos compile的 "-p" 这个参数设置没对
可能是你的android环境还没对

可以的话,等下周尝试下新的3.3rc1吧

**Comment by wijat** [comment]
我也以为是环境问题，但是我用2dx 3.3版本直接运行build目录下面的android-build.py是能编译过的。所以才纳闷嘛，关键是没文档说明3.3版本的很多新内容。。

**Comment by hugohuang1111** [comment]
在3.3rc0上的这个界面,最终调的还是 "cocos compile" 命令

文档这个的确是,正在处理这个文档这一块

**Comment by wijat** [comment]
顺便说一下，lua加密的文档似乎也没有，要是也有就好了。

**Comment by hugohuang1111** [comment]
quick提供了一个加密码的工具, quick/bin/compile_scripts.sh
直接带"-h"可以看到用法,

也可以上quick的论坛( http://www.cocoachina.com/bbs/thread.php?fid-56.html )搜索

单对于这个问题,还可以看这里
http://my.oschina.net/lonewolf/blog/178515

**Comment by SunLightJuly** [comment]
final版本的docs已经有详细说明
