### ISSUE TITLE
jdk 1.8 没法编译apk包

### ISSUE THREAD

**Issue by starwing** [dualface/v3quick#328]
得到这个错误：
···
exec: javac -encoding utf8 -target 1.6 -bootclasspath D:\adt-bundle-windows-x86_
64-20140702\sdk/platforms/android-20/android.jar -d D:\x\quick_test\frameworks\r
untime-src\proj.android\/bin/classes D:\x\quick_test\frameworks\runtime-src\proj
.android\/src\org\cocos2dx\lib\QuickHTTPInterface.java D:\x\quick_test\framework
s\runtime-src\proj.android\/src\org\cocos2dx\lua\AppActivity.java D:\x\quick_tes
t\frameworks\runtime-src\proj.android\/gen\com\example\quick_test\R.java -classp
ath D:\Work\Sources\v3quick\/quick/bin/android/libcocos2dx.jar;D:\x\quick_test\f
rameworks\runtime-src\proj.android\libs/libPluginProtocol.jar
javac: 目标发行版 1.6 与默认的源发行版 1.8 冲突

---

Error: javac error!!
build return value: 2
···

我这边在ApkBuilder里面给javac加了一个参数就OK了：

``` php
        $cmd_str = 'javac -encoding utf8 -target '. $this->java_version 
        . ' -source ' . $this->java_version
            . ' -bootclasspath ' . $this->boot_class_path 
            . ' -d ' . $classesPath;
```

这样的改进不会有问题吧？

**Comment by SunLightJuly** [comment]
-source参数是应该加的，谢谢指正
