### ISSUE TITLE
发现3.3使用Label的时候掉帧很严重（在wp8下测试的）

### ISSUE THREAD

**Issue by Hioln** [dualface/v3quick#329]
如题，这可能是框架问题  使用的系统字体 ttf 和 fnt测试  都有不同程度的严重掉帧

**Comment by Hioln** [comment]
测试代码（只是测试用）
for i = 1 , 500 do
        cc.ui.UILabel.new({
            UILabelType = 2,
            text = "111", 
            font = "Arial",
            size = 13,
            color = cc.c3b(255, 255, 255), 
            align = cc.ui.TEXT_ALIGN_CENTER
        })
        :align(display.CENTER, display.cx, display.cy)
        :addTo(self)
    end

**Comment by SunLightJuly** [comment]
wp8 的性能目前无解
