### ISSUE TITLE
WebView 支持

### ISSUE THREAD

**Issue by luoxinliang** [dualface/v3quick#335]
强烈建议支持WebView啊。显示动态的页面，比如游戏公告活动等，WebView是最佳方式。

**Comment by zhaozhantao** [comment]
就是就是

**Comment by xiyuera** [comment]
..自己加

**Comment by SunLightJuly** [comment]
cocos2dx支持的功能，3.3final版本之后已经自动支持

**Comment by yuyangame** [comment]
大神，真滴吗，为啥ccui.Helper是nil嘞 @SunLightJuly

**Comment by yuyangame** [comment]
2.26升级到3.3final ccs1.6升级到ccs2.06  
之后就纠结于ccs的textfield   的getString   getStringLen  setString全部报节点为nil  , getTag又正确返回
