### ISSUE TITLE
建议统一用cocos console

### ISSUE THREAD

**Issue by luoxinliang** [dualface/v3quick#343]
今天看了下 cocos console，这工具已经很屌，而且扩展很方便。http://www.cocos2d-x.org/wiki/Cocos2d-console。

有个疑问是，为什么quick不直接用这个？另外现在lua-binding已经由quick团队负责，从大局着想，各方面还是统一下。

**Comment by dualface** [comment]
quick 里没有用 cocos console 有几个原因：
-   quick 出现得比 cocos console 更早，所以发展了自己的一套工具
-   cocos console 需要用户再装一套 python 2.x，而 quick 的工具不需要依赖外部库
-   cocos console 由厦门团队维护，我们做针对 quick 的修改很难合并

不过未来 quick 和 cocos2d-lua 融合后，就统一使用 cocos console。
