### ISSUE TITLE
3.3rc1player只要有错，就会闪退，以前不会  

### ISSUE THREAD

**Issue by zhaozhantao** [dualface/v3quick#344]
以前用player，有错误，就会打印出错误来，但是不会闪退。现在是什么情况，只要有错，就退

**Comment by SunLightJuly** [comment]
我们未发现此情况，麻烦你提供更详细的现象说明，如使用的操作系统，最简化的重现路径等，让我们进行测试

**Comment by zhaozhantao** [comment]
我在3.3final的计划上找到了该错误的描述。
在 C/C++ 代码断言失败时，输出完整的 C/C++/Lua 调用栈，帮助开发者定位错误
正是我所遇到的问题，c++代码出错了，然后player就会闪退。

**Comment by SunLightJuly** [comment]
严重的C++代码出错肯定是无法完全处理的，我们的计划也只能尽量多处理一些情况

**Comment by zhaozhantao** [comment]
比如
local a = nil
a.attr = 1
这样就会闪退，而以前的player不会。以前的player只是报一下错就完了

**Comment by SunLightJuly** [comment]
这个不会啊。我刚刚试了一下，也只报错，不会闪退啊。mac和win的player都是正常的。

**Comment by SunLightJuly** [comment]
现在C++函数assert faile时提示调用出错的函数名称
