### ISSUE TITLE
报告几个QuickHTTPInterface.java的问题

### ISSUE THREAD

**Issue by xiyuera** [dualface/v3quick#356]
getResponedHeader
Header 处理时没有考虑 cookie 等header里只有 key 没有 值的情况 如 httponly 这类服务器不会回传 true 值。 

str2Seconds
服务器时间日期格式很多，此处经常会 try 出异常

访问到大量数据过程中，调用jni会崩溃。

**Comment by hugohuang1111** [comment]
嗯，正在处理

**Comment by hugohuang1111** [comment]
确定一个问题, 
"访问到大量数据过程中，调用jni会崩溃",
这个的意思就是调了start()后,再去设置参数吗

**Comment by xiyuera** [comment]
不是，请求发送之后立刻调用其他jni。可以请求一个比较大的下载文件测试。据我目测是因为jvm的多线程问题。

**Comment by xiyuera** [comment]
CCHttpRequestAndroid.cpp [line 541] void *HTTPRequest::requestCURL(void *userdata) 内 jvm 被 detach 了。对应的 vm 实际是一个单例。具体细节我就没往下看了。

**Comment by hugohuang1111** [comment]
是在detach前再去调用jni吧,比如通过luaj通过其它java函数之类这样吗

因为在detach后,接收线程其实都结束了

**Comment by xiyuera** [comment]
之前和之后都有调用多次 jni

**Comment by hugohuang1111** [comment]
在samples/tests加了个测试方式，没有重现，下载中，多次调用jni会崩溃的问题，
能否给出你的测试代码，以便我们调试

主要修改代码如下
samples/tests/src/tests/framework/networkTest.lua

function NetworkTestScene:ctor()

```
...........

self:startTimer()
```

end

function NetworkTestScene:createHTTPRequestTest()
    local url = "http://quick-x.com/feed/"
    url = "http://leweicn.onlinedown.net/down/onewifi-1.0.3.240.zip"

```
...........
```

end

function NetworkTestScene:startTimer()
    local scheduler = require("framework.scheduler")

```
local invokeJni = function()
    luaj.callStaticMethod(
        "org/cocos2dx/lua/AppActivity",
        "showLog",
        {"text " .. self.val},
        "(Ljava/lang/String;)V")
    self.val = self.val + 1
end
self.val = 1
self.timer = scheduler.scheduleGlobal(invokeJni, 0.1)
```

end

public class AppActivity extends Cocos2dxActivity{

```
static void showLog(String str) {
    Log.i("htl", "invoke success" + str);
}
```

}

**Comment by xiyuera** [comment]
不是通过LuaJ调用的。我找找能不能找到崩溃案例。可能没放版本库。
具体场景是前台一直有一个可触摸的Node。后台在使用CCHTTPRequest下载文件，完成后调用saveResponseData()存储到sdcard。表现出来的bug就是下载过程中，有触摸事件，即崩。不触摸表现良好。

**Comment by hugohuang1111** [comment]
触摸才崩溃,那就是触摸问题吧,与jni无关

嗯,帮忙给我们一个可以出现的样例吧

随便确认一下,是在V3上嘛,哪个版本

**Comment by xiyuera** [comment]
晚上回去写个

**Comment by hugohuang1111** [comment]
此问题我们验证后,未重现,关闭

@xiyuera  有可重现的具体步骤或代码,
请联系我们,reopen
我们一直保持关注
