### ISSUE TITLE
Need more documents about the project structure and workflow

### ISSUE THREAD

**Issue by thenewvu** [dualface/v3quick#358]
Hi there,

The project is awesome. I really want to contribute the project, but there are only few articles that talking about the project structure and how stuffs work together.

Could you add more documents about those topics, pls ?

**Comment by takaaptech** [comment]
Yes! I think we should have documents about folder structure! For example, we see assets folder in android project with full source code but do not know do this include in apk..

**Comment by hugohuang1111** [comment]
We welcome contributing code to our project really!
@thenewvu  you can send pull request to us.

the project is base on cocos2dx
quick
    bin    //tools for compile scripts, create project
    cocos  //cocos2dx's lua script file
   framework //quick's core framework
   lib   // quick's native code for framework
  player //as the name, player's relatvie code
  samples // samples for how to use quick framework
 welcome // player will run it, user can create project, compile project

the more detail document, we will add in the future
