### ISSUE TITLE
Android上 CC_USE_CURL = 1 时仍然使用的是java的http模块。

### ISSUE THREAD

**Issue by tangyiyang** [dualface/v3quick#378]
个人认为，
  Android上 CC_USE_CURL = 0 时使用的是java的http模块。
  CC_USE_CURL = 1应该使用libcurl模块请求http。

我已经在本地把这个feature改了。 不太会提PR。 T_T

**Comment by SunLightJuly** [comment]
quick建议在Android上使用原生java的http模块，如果需要curl模块可以自己修改。谢谢反馈！
