### ISSUE TITLE
全局变量,spc

### ISSUE THREAD

**Issue by lhfcode** [dualface/v3quick#393]
debug.lua中的dump函数 有个全局变量,spc

**Comment by lhfcode** [comment]
按钮加到层上无法回调,但把bPlugin_ 设置为false就可以,  测试发现创建层display.newLayer()是通过display.newNode()

**Comment by lhfcode** [comment]
NodeEx.lua 中有个意外的全局变量 listenerRet

**Comment by hugohuang1111** [comment]
1. 看commit c1123f6ffd8e3acc99e20cd6e6025643ab9e6644
2. 看commit b74d3bf977024012003bf0e214c23e9c5934926b
3. 这个我们没重现
   主要测试代码
   bPlugin_未作修改,在3.3上
   
   local layer = display.newLayer():addTo(self)
   
   cc.ui.UIPushButton.new("GreenButton.png", {scale9 = true})
       :setButtonSize(200, 60)
       :setButtonLabel(cc.ui.UILabel.new({text = "Use CCSLoader"}))
       :onButtonPressed(function(event)
           event.target:setScale(1.2)
       end)
       :onButtonRelease(function(event)
           event.target:setScale(1.0)
       end)
       :onButtonClicked(function(event)
           app:enterNextScene()
       end)
       :align(display.CENTER, display.cx, display.cy + 40)
       :addTo(layer)

**Comment by hugohuang1111** [comment]
按钮加到层上无法回调
我们验证后,未重现,关闭

@lhfcode 有可重现的具体步骤或代码,
请联系我们,reopen
我们一直保持关注
