### ISSUE TITLE
刚刚从升级3.3rc 升级到3.3final版本，lua加密的代码运行不了。

### ISSUE THREAD

**Issue by wijat** [dualface/v3quick#403]
之前我的项目是3.3rc版本，今天刚刚换了3.3final版本，然后加密的脚本就运行不了了。

脚本是用命令compile_scripts.bat加密的。
![qq 20150127200908](https://cloud.githubusercontent.com/assets/8220843/5918159/6f3e7612-a660-11e4-9ca8-6d3b0807c387.jpg)

执行cc.LuaLoadChunksFromZIP("res/game.zip")的时候报错。

**Comment by wijat** [comment]
## 报错信息：

LOAD LUA FILE: D:/myGameDir/wshRelease/src/main.lua

---

lua_loadChunksFromZIP() - load zip file: res/game.zip*

[LUA ERROR] load "app.battle.BattleArrayConfig", error: syntax error during pre-compilation.

[LUA ERROR] load "app.battle.BattleController", error: syntax error during pre-compilation.

[LUA ERROR] load "app.battle.BattleLogic", error: syntax error during pre-compilation.

[LUA ERROR] load "app.battle.element.models.Actor", error: syntax error during pre-compilation.

lua_loadChunksFromZIP() - loaded chunks count: 0

can not get file data of src/app/MyApp.lua

[LUA ERROR] [string "D:/myGameDir/wshRelease/src/main.lua"]:18: module 'app.MyApp' not found:
    no field package.preload['app.MyApp']
    no file '.\app\MyApp.lua'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\lua\app\MyApp.lua'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\lua\app\MyApp\init.lua'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\app\MyApp.lua'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\app\MyApp\init.lua'
    no file 'D:/myGameDir/wshRelease/src/app\MyApp.lua'
    no file 'src/'
    no file '.\app\MyApp.dll'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\app\MyApp.dll'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\loadall.dll'
    no file '.\app.dll'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\app.dll'
    no file 'D:\cocos\quick-cocos2d-x\quick\player\win32\loadall.dll

**Comment by dualface** [comment]
3.3final 把 luajit 替换为了 lua。所以字节码要重新编译。
