### ISSUE TITLE
quick/cocos/cocos2d/DrawPrimitives.lua 这个文件变量是不是写错了？

### ISSUE THREAD

**Issue by BorgLee** [dualface/v3quick#408]
第20行 dp_Initialized = true 这个变量 和 第2行的 local dp_initialized = false 这两个变量一个大写I，一个小写i。是不是写错了？虽然我不知道这个类是干嘛的。。。

**Comment by htlxyz** [comment]
感谢指出

https://github.com/dualface/v3quick/pull/409
