### ISSUE TITLE
Stencil buffer is not enabled

### ISSUE THREAD

**Issue by jayqqaa12** [dualface/v3quick#411]
win32  player 运行   cc.ClippingNode 设置遮罩  但是原来的背景变成 白色的
 提示    Stencil buffer is not enabled  

要如何设置 解决  3.3final 版本

**Comment by SunLightJuly** [comment]
请参考以下的commit:
https://github.com/dualface/v3quick/commit/b25d1a4b72b0a9a454ac7be275301039d1925a7c
