### ISSUE TITLE
touch事件分发的和穿透bug

### ISSUE THREAD

**Issue by liurenhua** [dualface/v3quick#413]
重现方法：
       多个层级不同的Node同时监听touch事件，上层的Node设置可以穿透事件，并当接收到Touch事件时打印出LOG，当点击某个按钮时重新创建这些Node

BUG现象描述：
        有一定概率（大约50次会出现一次）会出现层级在上层的node接收不到touch事件，而层级较低的会接收到touch事件，或者同一个node会接收到多次touch事件

重现简单demo源码：
local MainScene = class("MainScene", function()
    return display.newScene("MainScene")
end)

function MainScene:ctor()
    self:createButton()
end

function MainScene:createEat()
    n6 = self:make_eat_event_node(function() print("this zorder is 6") end):addTo(self, 6)
    n6:setTouchSwallowEnabled(false)
    n4 = self:make_eat_event_node(function() 
                        print("this zorder is 4") 
                        self:clearEat()  
             end):addTo(self, 4)
end

function MainScene:clearEat()
    n4:removeSelf()
        n6:removeSelf()
    self:createButton()
end

function MainScene:createButton()
    button = cc.ui.UIPushButton.new("Share/Button1.png")
        :onButtonPressed(function(event) event.target:setScale( event.target:getScale() + 0.1 ) end)
        :onButtonRelease(function(event) event.target:setScale( event.target:getScale() - 0.1 ) end)
        :addTo(self,9):pos(display.cx,display.cy)
        :onButtonClicked(function()
            button:removeSelf()
            self:createEat() 
        end)
end

function MainScene:make_eat_event_node(func)
    local eatEventNode = display.newLayer()
    eatEventNode:setTouchEnabled(true)
    eatEventNode:addNodeEventListener(cc.NODE_TOUCH_EVENT, function(event)
        if event.name == "began" and func then func() end
        return true
    end)

```
return eatEventNode
```

end

return MainScene

**Comment by quick-x-team** [comment]
此问题在处理中

**Comment by freeran** [comment]
昨天下午把项目升级到3.3，同时出现了touch闪退和同时给多个node注册touch事件时会有随机的一些node无法接收到touch事件的问题。

**Comment by freeran** [comment]
刚才简单测试了一下，貌似也是touch层级有问题

**Comment by tangyiyang** [comment]
这个bug看起来像是不能在EventDispatch里remove掉当前的那一个Event引起的。你delay到下一帧去remove，就不会出这种问题了。算是一个小坑吧。
