### ISSUE TITLE
quick cocos2dx 3.3Final版本触屏死机bug  

### ISSUE THREAD

**Issue by ghost** [dualface/v3quick#414]
测试环境windows
测试demo:  任何有触屏事件注册node的demo，  我这里用的例子是quick sample下的2048应用
测试代码:  将 local a = nil  a.b = 1  这两行代码加入MainScene ctor函数的末尾
测试方法：  启动模拟器进入2048,  会看见lua报错（正确, 因为我写的这个lua代码就是错误的）,  点击模拟器内部， 死机， 断点监控死在luaEventNode isRunning函数中
出现几率: 100%必现
bug推测：quick触屏机制设计缺陷导致， 在MainScene ctor中出现报错的lua代码，由lua语言报错机制导致MainScene add到屏幕的代码没有执行,  而MainScene内部按钮的LuaEventNode注册到了事件队列中， LuaEventNode对应的Node不存在 ，死机
bug影响： 在游戏软件运行中， 难免出现某个时刻lua代码在某个条件报错， 这时候玩家触摸屏幕会出现闪退！  后果相当严重， 用lua的一个好处就是解决玩家在玩游戏在某种未知bug出现时  不会出现闪退！

**Comment by quick-x-team** [comment]
此问题确实存在。由于最开始的指导思路是完全不修改原来2dx的Node类的代码，所以LuaEventNode的释放是在它对应的node的onCleanup消息里进行处理的；而如果一个node没有添加到屏幕上时，它释放时是不会发出onCleanup消息的，这就造成LuaEventNode还存在而它对应的Node的已经不存在的情况。
要解决这个问题，如果修改Node类的代码还是很简单的，只需要在Node的析构函数里释放对应的LuaEventNode就可以了。你可以先这样修改一下。quick平台这边还要先评估一下是否确定要修改Node类的代码，以及修改后对今后升级的影响如何进行处理。
谢谢你的反馈！

**Comment by ghost** [comment]
您好， CCNode的析构函数 并不会触发到libluacocos2d层啊， 并且NodeEx.lua中也没有相关方法在CCNode析构的时候触发， 这个问题如何解决， 自己在c++层编写触发机制的代码？

**Comment by SunLightJuly** [comment]
是的，就是因为原来的析构函数不会触发，才会有问题，所以要自己写。
现在当一个node在lua层收到oncleanup回调时，会调用removeTouchEvent()，对应C++里的tolua_Cocos2d_Node_removeTouchEvent()函数。
需要做的，就是参照tolua_Cocos2d_Node_removeTouchEvent()函数里的处理，在CCNode析构时作相应的调用。
