### ISSUE TITLE
websocket关于windows平台的bug

### ISSUE THREAD

**Issue by liurenhua** [dualface/v3quick#417]
问题描述：在windows7和windows8平台用websoket主动close连接的时候程序就会死掉，断点跟到websocket库里就陷入了死循环，但是在mac和android和ios平台不会出现这样的情况，有时候发送数据的时候程序也会陷入死循环，这种情况也只有在windows平台出现

**Comment by hugohuang1111** [comment]
@liurenhua 能不能给我们一个可以出现的测试样例,我们好重现啊

**Comment by liurenhua** [comment]
你好，demo如下：此demo在window平台会导致程序崩溃
local MainScene = class("MainScene", function()
    return display.newScene("MainScene")
end)

local WebSockets = class("WebSockets")

WebSockets.TEXT_MESSAGE = 0
WebSockets.BINARY_MESSAGE = 1
WebSockets.BINARY_ARRAY_MESSAGE = 2

WebSockets.OPEN_EVENT    = "open"
WebSockets.MESSAGE_EVENT = "message"
WebSockets.CLOSE_EVENT   = "close"
WebSockets.ERROR_EVENT   = "error"

function WebSockets:ctor(url)
    cc(self):addComponent("components.behavior.EventProtocol"):exportMethods()
    self.socket = cc.WebSocket:create(url)

```
if self.socket then
    self.socket:registerScriptHandler(handler(self, self.onOpen_), cc.WEBSOCKET_OPEN)
    self.socket:registerScriptHandler(handler(self, self.onMessage_), cc.WEBSOCKET_MESSAGE)
    self.socket:registerScriptHandler(handler(self, self.onClose_), cc.WEBSOCKET_CLOSE)
    self.socket:registerScriptHandler(handler(self, self.onError_), cc.WEBSOCKET_ERROR)
end
```

end

function WebSockets:isReady()
    return self.socket and self.socket:getReadyState() == cc.WEBSOCKET_STATE_OPEN
end

function WebSockets:send(data, messageType)
    if not self:isReady() then
        printError("WebSockets:send() - socket is't ready")
        return false
    end

```
messageType = checkint(messageType)
self.messageType = messageType
if messageType == WebSockets.TEXT_MESSAGE then
    self.socket:sendString(tostring(data))
elseif messageType == WebSockets.BINARY_ARRAY_MESSAGE then
    data = checktable(data)
    self.socket:sendString(data, table.nums(data))
else
    self.socket:sendString(tostring(data))
end
return true
```

end

function WebSockets:close()
    if self.socket then
        self.socket:close()
        self.socket = nil
    end
    self:removeAllEventListeners()
end

function WebSockets:onOpen_()
    self:dispatchEvent({name = WebSockets.OPEN_EVENT})
end

function WebSockets:onMessage_(message)
    local params = {
        name = WebSockets.MESSAGE_EVENT,
        message = message,
        messageType = self.messageType
    }

```
self:dispatchEvent(params)
```

end

function WebSockets:onClose_()
    self:dispatchEvent({name = WebSockets.CLOSE_EVENT})
    self:close()
end

function WebSockets:onError_(error)
    self:dispatchEvent({name = WebSockets.ERROR_EVENT, error = error})
end

function MainScene:ctor()
    if self.websocket then return end
    self.websocket = WebSockets.new("ws://echo.websocket.org")
    self.websocket:addEventListener(WebSockets.OPEN_EVENT, handler(self, self.onOpen))
    self.websocket:addEventListener(WebSockets.MESSAGE_EVENT, handler(self, self.onMessage))
    self.websocket:addEventListener(WebSockets.CLOSE_EVENT, handler(self, self.onClose))
    self.websocket:addEventListener(WebSockets.ERROR_EVENT, handler(self, self.onError))
end

function MainScene:onOpen(event)
    print("socket is connected, Ready to close the socket!")
    self:performWithDelay(function() self.websocket:close() print("socket close success!") end, 0.5)
end

function MainScene:onMessage(event)
    if WebSockets.BINARY_MESSAGE == event.messageType then
        printf("receive binary msg: len = %s, binary = %s", string.len(event.message), bin2hex(event.message))
    else
        printf("receive text msg: %s", event.message)
    end
end

function MainScene:onClose(event)
    self.websocket = nil
end

function MainScene:onError(event)
    printf("error %s", event.error)
    self.websocket = nil
end

return MainScene

**Comment by liurenhua** [comment]
CCLOG导致线程锁死了..
