### ISSUE TITLE
开发新 Welcome app

### ISSUE THREAD

**Issue by dualface** [dualface/v3quick#57]
新 Welcome app 基于新的 player 架构。

功能要求：
-   创建新项目
-   运行项目
-   删除项目
-   导出项目
-   查看 quick 自带示例
-   查看 Welcome app 使用帮助

设计图参考：

![welcome3](https://cloud.githubusercontent.com/assets/62318/3944785/9af8322e-2619-11e4-898f-9e619a24dc5f.png)

**Comment by anguskwan** [comment]
请问这个版本预计什么时候发布？谢谢，期待ing

**Comment by dualface** [comment]
里程碑的日期设置是本周五

**Comment by gaojiefeng** [comment]
请问能按照里程碑计划发布吗?

**Comment by ghost** [comment]
推迟到 3.2beta2 发布,
1. windows 尚未支持 relaunch / openNewPlayerWithProjectConfig / openProjectWithProjectConfig 接口
