### ISSUE TITLE
发布 v3.2beta3

### ISSUE THREAD

**Issue by dualface** [dualface/v3quick#60]
测试：
-   所有 sample 可以编译并运行
-   新建项目所有工程可以编译并运行
-   支持 Code IDE 调试（脚本和 C++ VS/XCode 联调）
-   HTTPRequest Java 版测试
-   新 Welcome app 测试
-   动态分辨率切换 sample

**Comment by fireyang** [comment]
有没有生成external下的类库的prebuilt的参考资料？

**Comment by dualface** [comment]
completed
