### ISSUE TITLE
player项目在mac下编译不过，改了libquick的prefix header设置也不行，求助

### ISSUE THREAD

**Issue by anguskwan** [dualface/v3quick#65]
![image](https://cloud.githubusercontent.com/assets/1006912/3951146/d9e5f21a-26d1-11e4-93ef-b80f4085635d.png)

我直接下载整个v3quick git的zip包，然后找到player的工程编译的，请指教哇，哪里有问题吶

**Comment by dualface** [comment]
运行一下 setup_mac.sh 后再重新打开 Xcode

**Comment by anguskwan** [comment]
![image](https://cloud.githubusercontent.com/assets/1006912/3951198/ee4ff984-26d2-11e4-84a6-800de82ea21b.png)

![image](https://cloud.githubusercontent.com/assets/1006912/3951196/e879139c-26d2-11e4-8ebb-e1fcf9227972.png)

请不要着急close ＝ ＝！

**Comment by dualface** [comment]
你打开的是 v3 的 player 工程，请运行 v3 里的 setup_mac.sh。而不是 v2 的。

QUICK_COCOS2DX_ROOT 是 v2 用的环境变量。v3 另外用了一个 QUICK_V3_ROOT。

**Comment by anguskwan** [comment]
好的，我再试试哈，谢谢

**Comment by anguskwan** [comment]
![image](https://cloud.githubusercontent.com/assets/1006912/3951323/41a33f64-26d4-11e4-9619-e200f466591c.png)

我搞错了～～

**Comment by dualface** [comment]
啊，那我们把这个 setup 删除掉，多余了。。。
