### ISSUE TITLE
创建 3.2 宣传网页

### ISSUE THREAD

**Issue by dualface** [dualface/v3quick#71]
TODO：
-   用图形和数据列出 3.2 和 v2/原版cocos 的区别及改进
-   适应桌面浏览器和移动浏览器
-   现有功能总结
-   后续功能展望

**Comment by dualface** [comment]
由峻峰提供下列数据：
-   模块化编译机制下，每一个可选模块占用的 so 空间
-   去掉所有可选模块后的 so 大小
-   以 release 模式的编译结果为准

**Comment by gaojiefeng** [comment]
开始准备文档和宣传网页了，看来已经差不多了啊

**Comment by dualface** [comment]
completed
