### ISSUE TITLE
在Scale9Sprite上添加子节点的ZOrder必须大于2 

### ISSUE THREAD

**Issue by bigHandYT** [dualface/v3quick#92]
查看了Scale9Sprite源码，在Scale9Sprite的updateWithBatchNode 函数中把9个小图片都加到Scale9Sprite的自身节点上了，并且设置ZOrder,
于v2.2.5做了下对比v2.2.5 是把9个小图片加在了Scale9Sprite的子节点_scale9Image 上的。
不知道V3 中 这个做法的原因是什么.

**Comment by SunLightJuly** [comment]
cocos2dx 3.x作此修改的原因仍不明，暂时延后处理
